[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[rpc_endpoints]
bsc = "https://bsc-dataseed1.binance.org"
bsc_testnet = "https://data-seed-prebsc-1-s1.binance.org:8545"

[etherscan]
bsc = { key = "${BSC_API_KEY}" }
